spring:
  application:
    name: cloudRepo
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_repo
    username: postgres
    password: 1627
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6380
  session:
    store-type: redis
    timeout: 3000
    redis:
      namespace: spring:session
      flush-mode: on_save
server:
  servlet:
    context-path: /api
